language: java
jdk:
  - oraclejdk8
install:
  - mvn --settings .travis/settings.xml install -B -V
before_install:
  -
    provider: script
    script: .travis/deploy.sh
before_deploy:
  - git reset --hard
deploy:
  -
    provider: script
    script: .travis/deploy.sh
    on:
      branch: master
      jdk: oraclejdk8
