language: java
jdk:
  - oraclejdk8
install:
  - mvn --settings .travis/settings.xml install -B -V
before_install:
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then $GPG_EXECUTABLE  --list-keys; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then $GPG_EXECUTABLE  --keyserver hkp://pool.sks-keyservers.net --send-keys 682D6268; fi'
before_deploy:
  - git reset --hard
deploy:
  -
    provider: script
    script: .travis/deploy.sh
    on:
      branch: master
      jdk: oraclejdk8
